version: 2.1

jobs:
  build-and-deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          version: default
      - run:
          name: Build Docker Image
          command: |
            docker build -t sanjaysir01/readytomovie:latest .
      - run:
          name: Push to Docker Hub
          command: |
            echo "$docker_password" | docker login -u "$docker_username" --password-stdin
            docker push sanjaysir01/readytomovie:latest
      - add_ssh_keys:
          fingerprints:
            - "SHA256:uCtOaAnO5Ry9H0y2uy0j5RjqniUljjkaR+fC4zyUF0I"
      - run:
          name: Add VPS to known hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $host >> ~/.ssh/known_hosts
      - run:
          name: Deploy on VPS
          command: |
            ssh $vps_user@$host "
              docker pull sanjaysir01/readytomovie:latest &&
              docker stop readytomovie_frontend_container || true &&
              docker rm readytomovie_frontend_container || true &&
              docker run -d \
                --name readytomovie_frontend_container \
                -v /var/www/projects/readytomovie/Ready2Move/.env:/app/.env \
                -p 6001:6001 \
                --restart unless-stopped \
                sanjaysir01/readytomovie:latest
            "

workflows:
  build-test-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
